// FIREBASE Reference

//
// Set up your DB:
//
// You need to put the name of your endpoint (ie. what kind of data are you storing?)
// as an argument to the ref function.
// For example, if we were storing cats, we would write:
// const service = firebase.database().ref("cats");

//
// Create:
//
// const cat = {
//   name: "Milano",
//   age: 7,
//   favoriteFoods: ["tuna", "squid", "chicken"]
// };
// service.push(cat);

//
// Read:
//
// let cats = {};
// service.on("value", function(snapshot) {
//   cats = snapshot.val();
//   // Do DOM manipulation with cats variable here.
//   // NOTE: cats is an object with a key (generated by Firebase)
//   // for each cat you added, set to the value of each cat
//   // that you added

//   // Based on our example, the cats variable would look something like:
//   // {
//   //   "-LHaKIAIZ8-W0feX_Dz5": {
//   //     name: "Milano",
//   //     age: 7,
//   //     favoriteFoods: ["tuna", "squid", "chicken"]
//   //   }
//   // }
// });

//
// Update:
//
// You need to pull the key out from the DOM.
// const key = $(this)
//   .parent()
//   .data("key");
// service.child(key).update({
//   age: 8
// });

//
// Delete:
//
// You need to pull the key out from the DOM.
// const key = $(this)
//   .parent()
//   .data("key");
// service.child(key).remove();

const service = firebase.database().ref("posts");
let data = {};

$("#post").on("click", function() {
  service.push({
    name: $("#message").val(),
    likes: 0
  });

  $("#message").val("");
});

service.on("value", function(snapshot) {
  $("#message-board").empty(); // clear board of all posts and rerender based on what's in Firebase

  data = snapshot.val() || {}; // store data in a global variable for calculating likes/dislikes later

  // Loop through the keys
  const itemKeys = Object.keys(data);
  for (let i = 0; i < itemKeys.length; i++) {
    const key = itemKeys[i];
    const item = data[key];

    // we encode the key using a data attribute
    const template = `
      <li data-key=${key}>
        ${item.name}
        <i class="fa fa-trash pull-right delete"></i>
        <i class="fa fa-thumbs-down pull-right dislike"></i>
        <i class="fa fa-thumbs-up pull-right like"></i>
        <span class="pull-right likes">${item.likes}</span>
      </li>
    `;

    $("#message-board").append(template);
  }
});

$("#message-board").on("click", ".delete", function() {
  const key = $(this)
    .parent() // use use "parent()" here since the data-key is on the li
    .data("key");

  service.child(key).remove();
});

$("#message-board").on("click", ".like", function() {
  const key = $(this)
    .parent() // use use "parent()" here since the data-key is on the li
    .data("key");

  service.child(key).update({
    likes: data[key].likes + 1
  });
});

$("#message-board").on("click", ".dislike", function() {
  const key = $(this)
    .parent() // use use "parent()" here since the data-key is on the li
    .data("key");

  service.child(key).update({
    likes: data[key].likes - 1
  });
});
